version: '3.7'
services:
  php:
    build:
      args:
        user: ${CURRENT_HOST_USER}
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME_PREFIX}-php
    volumes:
      - ./${PROJECT_DIR}:/var/www

  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_NAME_PREFIX}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./${PROJECT_DIR}:/var/www
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    container_name: ${CONTAINER_NAME_PREFIX}-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - './docker/mysql:/var/lib/mysql'
#
#  postgres:
#    image: postgres:14.1-alpine
#    container_name: ${CONTAINER_NAME_PREFIX}-postgres
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - './docker/postgres:/var/lib/postgresql/data'

#
#  redis:
#    container_name: redis
#    image: redis:latest
#    restart: always
#    entrypoint: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} --maxmemory 512mb --maxmemory-policy allkeys-lru
#    ports:
#      - "6379:6379"
#    volumes:
#      - './docker/redis/data:/data'
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
